### ISSUE TITLE
USER STORY: Navbar

### ISSUE THREAD

**Issue by MiaRasmussen05** [MiaRasmussen05/craftconnect-frontend#1]
As a **user** I can **see the navbar on every page** so that **I can easily move around the app**.

**Criteria**

- The navbar should present a different layout that is suited to the screen size it is being viewed from.
- The navbar should be visible on every page and inform users of their current location and where they can go on the app.

**Todo's:**

- [x] Create Navbar component
- [x] Make NavBar responsive
- [x] Create costume css - navbar.module.css
- [x] Decide on final pages for the app
- [x] Fix site routing
