### ISSUE TITLE
USER STORY: Authentication - Sign up

### ISSUE THREAD

**Issue by MiaRasmussen05** [MiaRasmussen05/craftconnect-frontend#2]
As a **user** I can **register for a new account** so that **I can post, share, view and follow people and content on the app**.

**Criteria**

- Users can register with a unique username and a password.

**Todo's:**

- [x] Create sign up form
- [x] Create sign up link on NavBar
- [x] Connect to API
- [x] Send data to API
