### ISSUE TITLE
USER STORY: Authentication - login/logout

### ISSUE THREAD

**Issue by MiaRasmussen05** [MiaRasmussen05/craftconnect-frontend#3]
As a **user** I can **login as well as logout of my private account** so that **I can use the app with my credentials when needed**.

**Criteria**

- Users can sign in using the credentials they used to sign up with.
- Users can logout just as easily with a logout button.

**Todo's:**

- [x] Create login form
- [x] Create EventHandlers for username and password
- [x] Create login and logout link on NavBar
- [x] Create a redirect so that successful login will redirect to the home page
