### ISSUE TITLE
USER STORY: Navbar: Conditional rendering

### ISSUE THREAD

**Issue by MiaRasmussen05** [MiaRasmussen05/craftconnect-frontend#4]
As a **visitor** I can **see the sign up and login button** so that **I can decide to sign up or login**.

**Criteria**

- Visitors still need to see the home page as well the options to login and signup. However not be able to do anything but read and see profiles.

**Todo's:**

- [x] Create home page
- [x] Redirect so that visitors land on the home page with a restricted navbar
- [x] Not be able to do anything but read and walk around on pages all users can see
