### ISSUE TITLE
USER STORY: Profiles

### ISSUE THREAD

**Issue by MiaRasmussen05** [MiaRasmussen05/craftconnect-frontend#5]
As a **user** I can **view other profiles and avatars** so that **I can see there posts and learn more about the person**.

**Criteria**

- Users all have a profile where there posts show up and other users can read what they put out.

**Todo's:**

- [x] Create profile header
- [x] Create profile about page
- [x] Display posts
- [x] List of who they follow
- [x] To follow or unfollow the user
- [x] Edit the profile
