### ISSUE TITLE
USER STORY: Posts

### ISSUE THREAD

**Issue by MiaRasmussen05** [MiaRasmussen05/craftconnect-frontend#6]
As a **user** I can **create a post or event to share** so that **others on the app can read about it as well**.

**Criteria**

- Only logged in user can post something.

**Todo's:**

- [x] Posts page layout
- [x] Users can like an unlike each one as well as comment
- [x] Posts should all be in the same place
- [x] Both one for all posts of all users and on a users profile for the people they follow and there own posts
- [x] Posts that have just been shared moved the last one down
