### ISSUE TITLE
USER STORY: Search bar

### ISSUE THREAD

**Issue by MiaRasmussen05** [MiaRasmussen05/craftconnect-frontend#7]
As a **user** I can **search for users, posts and events with keywords** so that **I can find what or who I am looking for quicker**.

**Criteria**

- The search bar is visible and usable to all users

**Todo's:**

- [x] Add search bar to navbar
- [x] Create the criteria 
- [x] Decided on all items that should be searchable
