### ISSUE TITLE
USER STORY: Comments

### ISSUE THREAD

**Issue by MiaRasmussen05** [MiaRasmussen05/craftconnect-frontend#9]
As a **user** I can **view comments from other users** so that **I can stay in touch with the community**.

**Criteria**

- Users can view comments left on posts and answer with there own

**Todo's:**

- [x] Create comments component
- [x] Decide on where comments should be possible
- [x] User should only be able to delete and update their own comments
